variables:
  PIP_CACHE_DIR: "$CI_PROJECT_DIR/.cache"

cache:
  paths:
    - .cache

test:
  stage: test
  image: 'python:3.7'
  script:
    - python3.7 -m pip install pycodestyle pylint mypy lxml
    - python3.7 setup.py test
    - python3.7 -m pycodestyle medmij
    - python3.7 -m pylint medmij
    - python3.7 -m mypy medmij

pages:
  stage: deploy
  image: 'hrektts/doxygen'
  script:
    - doxygen
    - mv html public
  artifacts:
    paths:
      - public
